source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ReactNativeMobileMessaging' do
    pod 'MobileMessaging/Core', '6.0.8'
    pod 'MobileMessaging/Geofencing', '6.0.8'
end
