source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ReactNativeMobileMessaging' do
    pod 'MobileMessaging/Core', '6.0.0', :path = '~/Users/akadochnikov/infobip-mobile-messaging-ios'
end